vector.o: ./vector.c
	gcc -c ./vector.c -I ./Header\ Files -o build/vector.o

s_stack: ./stack.c ./vector.c
	gcc ./stack.c ./vector.c -I./Header\ Files -o s_stack

s_queue: ./queue.c ./vector.c
	gcc ./queue.c ./vector.c -I./Header\ Files -o s_queue
